name: Hub
version: 1.1
main: fr.cel.hub.Hub
api-version: 1.21
author: Cel
depend: [GameAPI]
commands:
  hub:
    description: Besoin d'expliquer ? Bon. Permet d'aller au hub
  event:
    description: Permet d'effectuer des événements au Hub
    permission: hub.event
permissions:
  hub.event:
    description: Permission qui permet d'effectuer des événements