name: Hub
version: 1.1
main: fr.cel.hub.Hub
api-version: 1.21
author: Cel
depend: [GameAPI]
commands:
  hub:
    description: Besoin d'expliquer ? Bon. Permet d'aller au hub
  head:
    description: Permet de voir son avancée des tête trouvées dans le Hub
    aliases: [heads]
  event:
    description: Permet d'effectuer des événements au Hub
    permission: hub.event
  calculheads:
    description: Donne le nombre de têtes du Hub
    permission: hub.calculheads
  addhead:
    description: Permet d'ajouter une tête au Hub
    permission: hub.addhead
permissions:
  hub.event:
    description: Permission qui permet d'effectuer des événements
  hub.calculheads:
    description: Permission qui permet de donner le nombre de têtes du Hub
  hub.addhead:
    description: Permission qui permet d'ajouter une tête au Hub