name: Hub
version: '${project.version}'
main: fr.cel.hub.Hub
api-version: 1.19
depend: [GameAPI]
author: Cel
description: To make the NPCs, I used code from the FancyNpcs plugin.
commands:
  hub:
    description: Besoin d'expliquer ? Bon. Permet d'aller au hub
  event:
    description: Permet d'effectuer des événements
    permission: hub.event
  npc:
    description: Permet de gérer les NPCs
    permission: hub.npc

permissions:
  hub.event:
    description: Permet d'effectuer des événements
  hub.npc:
    description: Permet de gérer les NPCs