name: Parkour
version: ${project.version}
main: fr.cel.parkour.Parkour
api-version: 1.20
author: Cel
depend: [GameAPI]
commands:
  parkour:
    description: La commande principale
    permission: parkour.parkour
    aliases: [jump]