name: Parkour
version: 1.0.1
main: fr.cel.parkour.Parkour
api-version: 1.21
author: Cel
depend: [GameAPI]
commands:
  parkour:
    description: La commande principale
    permission: parkour.parkour
    aliases: [jump]