name: ValoCraft
version: '1.0'
main: fr.cel.valocraft.ValoCraft
api-version: 1.20
authors: [ Cel, Deadsky ]
depend: [GameAPI]
commands:
  valocraft:
    description: La commande principale
    permission: valocraft.valocommand