name: Essentials
version: 1.0
main: fr.cel.essentials.Essentials
author: Cel
api-version: 1.21
commands:
  heal:
    description: Permet de se soigner les joueurs
    permission: essentials.heal
  feed:
    description: Permet de se rassasier les joueurs
    permission: essentials.feed
  craft:
    description: Permet d'ouvrir un établi
    aliases: [workbench]
    permission: essentials.craft
  gm:
    description: Permet de changer le mode de jeu des joueurs
    permission: essentials.gm
  top:
    description: Permet de se téléporter à la surface
    permission: essentials.top
  nv:
    description: Permet de se donner l'effet Vision Nocturne
    aliases: [nightvision]
    permission: essentials.nv
  bc:
    description: Permet d'envoyer un message que tous les joueurs verront
    aliases: [broadcast]
    permission: essentials.bc
  speed:
    description: Permet de changer la vitesse des joueurs
    permission: essentials.speed
  ec:
    description: Permet d'ouvrir le coffre de l'end des joueurs
    aliases: [enderchest]
    permission: essentials.ec
  anvil:
    description: Permet d'ouvrir une enclume
    permission: essentials.anvil
  hat:
    description: Permet de mettre l'objet qu'il a dans sa main sur sa tête
    permission: essentials.hat
  near:
    description: Permet de savoir quels sont les joueurs autour du joueur
    permission: essentials.near
  god:
    description: Permet de mettre le mode invulnérable sur les joueurs
    permission: essentials.god
  discord:
    description: Donne le lien discord aux joueurs
  fly:
    description: Permet de mettre le vol au joueur
    permission: essentials.fly
  barrier:
    description: Commande qui donne un bloc de barrièer à un joueur
    permission: gameapi.barrier