name: Essentials
version: 1.0
main: fr.cel.essentials.Essentials
author: Cel
api-version: 1.21
commands:
  heal:
    description: Permet de se soigner
    permission: essentials.heal
  feed:
    description: Permet de se rassasier
    permission: essentials.feed
  gm:
    description: Permet de changer de mode de jeu
    permission: essentials.gm
  top:
    description: Permet de se téléporter à la surface
    permission: essentials.top
  nv:
    description: Permet de donner l'effet Vision Nocturne
    aliases: [nightvision]
    permission: essentials.nv
  bc:
    description: Permet d'envoyer un message sur tout le serveur que tous les joueurs verront
    aliases: [broadcast]
    permission: essentials.bc
  speed:
    description: Permet de changer la vitesse de marche/vol
    permission: essentials.speed
  hat:
    description: Permet de mettre n'importe quel objet que l'on a en main sur sa tête
    permission: essentials.hat
  near:
    description: Permet de savoir quels sont les joueurs à proximité
    permission: essentials.near
  god:
    description: Permet d'être invulnérable
    permission: essentials.god
  discord:
    description: Donne le lien Discord
  fly:
    description: Permet le vol
    permission: essentials.fly
  barrier:
    description: Donne un bloc de barrière invisible
    permission: gameapi.barrier