name: Cache-Cache
version: '${project.version}'
main: fr.cel.cachecache.CacheCache
api-version: '1.20'
authors: [ Cel, Deadsky666 ]
depend: [GameAPI]
commands:
  cachecache:
    description: Commande principale pour le plugin Cache-Cache
    permission: cachecache.cachecache
    aliases: [cc]