name: Cache-Cache
version: '1.2'
main: fr.cel.cachecache.CacheCache
api-version: 1.21
authors: [Cel, Deadsky]
depend: [GameAPI]
commands:
  cachecache:
    description: Commande principale pour le plugin Cache-Cache
    permission: cachecache.cachecache
    aliases: [cc]