name: EldenRPG
version: '${project.version}'
main: fr.cel.eldenrpg.EldenRPG
authors: [Cel, Deadsky]
api-version: '1.20'
description: To make the NPCs, I used code from the FancyNpcs plugin.
depend: [WorldGuard]
commands:
  npc:
    description: Permet de faire apparaître un PNJ
  quest:
    description: Permet de gérer les quêtes