name: GameAPI
version: '${project.version}'
main: fr.cel.gameapi.GameAPI
api-version: '1.20'
commands:
  friends:
    description: Commande pour le système d'amis
    aliases: [f, friend, ami, amis]
  register:
    description: Permet de s'enregistrer
  login:
    description: Permet de se connecter
  changepsw:
    description: Permet de changer son mot de passe
    aliases: [changepassword]
  afterrl:
    description: Commande à faire juste après un /reload
    permission: gameapi:afterrl
  coins:
    description: Commande pour le système de pièces
    aliases: [ coin, pieces, piece ]
    permission: gameapi.coins