name: Valocraft
version: 1.0.1
main: fr.cel.valocraft.Valocraft
api-version: 1.21
authors: [ Cel, Deadsky ]
depend: [ GameAPI ]
commands:
  valocraft:
    description: La commande principale
    permission: valocraft.valocommand
    aliases: [valo]